### ISSUE TITLE
USER STORY: View homepage

### ISSUE THREAD

**Issue by adamhatton** [adamhatton/john-breedon-bass-tuition-pp4#1]
As a site user
I want to be able to view information about the tutoring service
So that I can make an informed decision about using it

## Acceptance Criteria
* Information should be provided on homepage
* Information should include details about the services provided and the costs
* Information should be easy to read and styled to meet accessiblity guidelines

## Tasks
- [x] Create the view
- [x] Create the template
- [x] Connect the view in the urls file
- [x] Add javascript for scrollspy
