### ISSUE TITLE
USER STORY: View Booking Availability

### ISSUE THREAD

**Issue by adamhatton** [adamhatton/john-breedon-bass-tuition-pp4#14]
As a site user
I want to be able to view booking availability
So that I can find a time to book that suits me

## Acceptance Criteria
* Booking availability should be provided on a separate page
* Should display available bookings in hour long slots for the next week
* Bookings which are taken should be displayed as 'Booked'
* Information should be easy to read and styled to meet accessibility guidelines

## Tasks
- [x] Create new app
- [x] Create the view
- [x] Create the template
- [x] Connect the view in the urls file
- [x] Add navlink to base.html template
- [x] Add logic to show available slots from database
