### ISSUE TITLE
USER STORY: Create a booking

### ISSUE THREAD

**Issue by adamhatton** [adamhatton/john-breedon-bass-tuition-pp4#15]
As a site user
I want to be able to book a session
So that I can make use of the tutoring service

## Acceptance Criteria
* Should only be available to users that are logged in
* Booking should be presented as a submission form
* Slots should be clickable and should populate the booking form with the relevant time
* Booking form should include booking date, booking time, phone and lesson type
* Users should receive a confirmation message once the booking form is submitted

## Tasks
- [x] Create booking model
- [x] Add model to admin site
- [x] Create BookingForm class
- [x] Add form to template
- [x] Add form to view
- [x] Add confirmation message
- [x] Add logic to view to stop duplicate bookings
- [x] Add min and max limits to the date picker
- [x] Add javascript to slot buttons to prepopulate booking form
