### ISSUE TITLE
USER STORY: Update a booking

### ISSUE THREAD

**Issue by adamhatton** [adamhatton/john-breedon-bass-tuition-pp4#16]
As a site user
I want to be able to update a booking
So that I change bookings in line with my schedule

## Acceptance Criteria
* Existing bookings should have an 'Update' button next to them
* When the 'Update' button is pressed, the user should be taken to the booking availability page
* When the user completes the new booking, it should update the existing booking
* The user should receive a confirmation message that the booking has been updated

## Tasks
- [x] Add update button to template
- [x] Add new  class view for editing specific booking instances
- [x] Add logic to prevent duplicate bookings
- [x] Add duplicate error message
- [x] Add updated confirmation message
- [x] Add login decorator to url
- [x] Add auth check to ensure correct user is updating the booking
