### ISSUE TITLE
USER STORY: Delete a booking

### ISSUE THREAD

**Issue by adamhatton** [adamhatton/john-breedon-bass-tuition-pp4#17]
As a site user
I want to be able to delete a booking
So that I can cancel any bookings I can no longer make

## Acceptance Criteria
* Existing bookings should have a 'delete' button next to them
* When the 'delete' button is pressed, the user's booking should be removed from the database
* The user should receive a confirmation message that the booking has been deleted

## Tasks
- [x] Add delete button to template
- [x] Add view for deleting bookings
- [x] Add javascript for displaying the 'confirm deletion' modal
- [x] Add auth check to prevent deletion of bookings not owned by user
- [x] Add 'booking delete' confirmation message
