### ISSUE TITLE
USER STORY: View Created Bookings

### ISSUE THREAD

**Issue by adamhatton** [adamhatton/john-breedon-bass-tuition-pp4#18]
As a site user
I want to be able to view any bookings I have made
So that I can remind myself of what I have booked

## Acceptance Criteria
* Users should be able to view their bookings from their Account page
* The user's bookings should be displayed on screen
* Past bookings should not be displayed
* Information should be easy to read and styled to meet accessibility guidelines

## Tasks
- [x] Add booking section to template
- [x] Get bookings from DB and add to template context
- [x] Add logic to filter out old bookings
