### ISSUE TITLE
USER STORY: Contact Form

### ISSUE THREAD

**Issue by adamhatton** [adamhatton/john-breedon-bass-tuition-pp4#3]
As a site user
I want to be able to contact the tutor
So that I can ask questions

## Acceptance Criteria
* Ability to contact should be presented as a Contact Form
* Fields should include Name, email address, phone, and message
* Form should appear on the homepage
* Form should contain standard validation to ensure fields are completed
* Once submitted, a confirmation message should be provided

## Tasks
- [x] Create Contact Model
- [x] Include Contact Model in admin
- [x] Create Contact Form template
- [x] Include contact form submission in view code
- [x] Implement crispy forms configuration
- [x] Add confirmation message
- [x] Auto-scroll to form when there are errors
- [x] Reset form when it is valid and successful
