### ISSUE TITLE
USER STORY: Register an account

### ISSUE THREAD

**Issue by adamhatton** [adamhatton/john-breedon-bass-tuition-pp4#5]
As a site user
I want to be able to register an account
So that I can use the site functionality

## Acceptance Criteria
* Registration should require user to select a username and password
* Validation should be in place on the password to ensure it is complex
* User should be required to create a unique username
* User should be able to get to the registration process from the navigation bar
* User should be notified of successful registration
* Registration form should match the style of the website

## Tasks
- [x] Install django allauth
- [x] Edit allauth templates
- [x] Add register/login/logout to navigation bar
- [x] Change allauth configuration to make email mandatory
