### ISSUE TITLE
USER STORY: View Account page

### ISSUE THREAD

**Issue by adamhatton** [adamhatton/john-breedon-bass-tuition-pp4#7]
As a site user
I want to be able to see my account information
So I can remind myself of the information I entered

## Acceptance Criteria
* Account information should be provided in a separate 'Account page'
* Page should show the user's username, name, email, phone and their playing ability
* Should only be available to users that are logged in

## Tasks
- [x] Create view
- [x] Create Template
- [x] Add view into urls.py
- [x] Add account link into navbar
- [x] Create User and Profile forms
- [x] Add javascript for enabling inputs to be edited
- [x] Add instance to view to prepopulate form
