### ISSUE TITLE
USER STORY: Update Account Info

### ISSUE THREAD

**Issue by adamhatton** [adamhatton/john-breedon-bass-tuition-pp4#8]
As a site user
I want to be able to update account information
So I can keep my details up to date

## Acceptance Criteria
* User should be able to click an 'Update' button to update their details
* User should be able update all information on their account page
* User should be able to cancel the amend so that no change is made
* User should be given a 'submit' button to confirm their amendment
* User should be shown a message that their amendment has been made

## Tasks
- [x] Add buttons (update, cancel, submit) to template
- [x] Set cancel button to redirect to account page
- [x] Add post method to view
- [x] Add message to view
- [x] Add confirmation modal for submitting update
