### ISSUE TITLE
USER STORY: View Testimonials

### ISSUE THREAD

**Issue by adamhatton** [adamhatton/john-breedon-bass-tuition-pp4#9]
As a site user
I want to be able to view testimonials about the service
So that I can make an informed decision about using it

## Acceptance Criteria
* Testimonials should be provided on the about page
* They should include the following information: Name and content
* Information should be easy to read and styled to meet accessiblity guidelines

## Tasks
- [x] Create the view
- [x] Create the template
- [x] Connect the view in the urls file
- [x] Add code to view that gets random selection of testimonials
